'''File containg locaters to all elements'''
usernameInput = "txtLoginId"
passwordInput = "txtPassword"
loginButton = "Imagebutton1"
loginErrorPassword = "lblError"
branchSelector = "//*[contains(text(), '<BRANCH>')]"
CNNoInput = "txtLrRefNo"
CNRefDateInput = "txtLRRefDt"
CustomerNameSelect = "//select[@id='DrpCustomer']/option[text()='<CUSTOMERNAME>']"
DINoInput = "txtOrdNo"

vehicleNoSelect = "//select[@id='ddlVehicleNo']/option[text()='<VEHICLENO>']"
vehicleTypeInput = "txtVehType"
hiredFromSelect= "//select[@id='drpBroker']/option[text()='<HIREDFROM>']"
broker_transporterLocationSelect = "//select[@id='drpBrkLoc']/option[text()='<BROKER/TRANSPORTER_LOCATION>']"
ownerNameInput = "txtOwnerName"
ownerPhoneNumberInput = "txtOwnerPhNo"
contactPersonNameInput = "txtContactPers"
contactPersonNumberInput = "txtContactPersPhNo"
driverNameInput = "txtDriverName"
driverPhoneNumberInput = "txtDriverPhNo"
phoneNumber1Input = "txtDriverPhNo1"
phoneNumber2Input = "txtDriverPhNo2"
loadingSupervisorNameSelect = "//select[@id='DrpEmployeeID']/option[text()='<LOADINGSUPERVISORNAME>']"
toStationSelect = "//select[@id='ddlToStation']/option[text()='<TOSTATION>']"
fromStationSelect = "//select[@id='ddlFromStation']/option[text()='<FROMSTATION>']"
routeSelect = "//select[@id='ddlRoute']/option[text()='<ROUTE>']"
EGPNumberInput = "txtInoviceNo"
EGPDateTimeInput = "txtCAIDate"
productNameSelect = "ddlProductName"
freightOnSelect = "//select[@id='ddlFreghtOn']/option[text()='<FREIGHTON>']"
noOfPackagesInput = "txtNoPak"
materialTypeSelect = "ddlPices"
grossRateInput = "txtMatRate"
netRateInput = "txtWithoutDiesel"
UOMSelect = "//select[@id='ddlUOM']/option[text()='<UOM>']"
grossWeightInput = "txtGrossWt"
netWeightInput = "txtNetwt"
totalGrossAmount = "txtvaluematerial"
totalNetAmount = "txtWithoutDieselTo"
addMaterialDetailsButton = "Cmd_add"
cancelMaterialDetailsButton = "Cmd_Cancel"
partyNameSelect = "//select[@id='ddlPartyname']/option[text()='<PARTYNAME>']"

ewayBillNumberInput = "txteWayBill"
vehicleReleasedBySelect = "//select[@id='ddlVhicileRelesedBy']/option[text()='<VEHICLERELEASEDBY>']"
partyTypeSelect = "//select[@id='ddlPartyType']/option[text()='<PARTYTYPE>']"
partyNameSelect = "//select[@id='ddlPartyname']/option[text()='<PARTYNAME>']"
saveButton = "cmdAdd"

statusForLREntry = "lblErrorMsg"

'''<wnd app='iexplore.exe' cls='#32770' title='Message from webpage' />
<wnd app='iexplore.exe' cls='#32770' title='Message from webpage' />
<wnd ctrlid='2' title='OK' />'''